site_name: GoPoux 的笔记本
site_url: https://note.gopoux.cc/
repo_name: GoPoux4/notebook
repo_url: https://github.com/GoPoux4/notebook/
copyright: Copyright &copy; 2023-2024 GoPoux <a href="https://beian.miit.gov.cn/" target="_blank">蜀ICP备2023017648号</a>

theme:
  name: material
  language: 'zh'
  favicon: 'assert/ico/favicon.png'
  icon:
    repo: fontawesome/brands/github
    logo: material/notebook-outline
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
  font:
    text: Fira Sans
    code: Fira Mono

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GoPoux4
      name: My Github Page
    - icon: fontawesome/solid/rss
      link: https://www.cnblogs.com/syc233/
      name: My Cnblog Page

extra_css:
  - css/counter.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
  - Computer Science:
    - Computer Science: cs/index.md
    - 人工智能引论: cs/intro_to_ai/ai.md
    - 计算机逻辑设计基础:
      - cs/computer_logic/index.md
      - 数字系统和信息: cs/computer_logic/chapter1.md
      - 组合逻辑电路: cs/computer_logic/chapter2.md
    - 量子计算:
      - Basic Definition: cs/quantum/introduction.md
  - Math:
    - Math: math/index.md
    - 概率论:
      - math/prob_theory/index.md
      - 事件及其概率: math/prob_theory/chapter1.md
      - 随机变量与分布函数: math/prob_theory/chapter2.md
      - 数学期望: math/prob_theory/chapter3.md
  - HPC:
    - HPC: hpc/index.md
    - cute:
      - cute: hpc/cute/index.md
      - Layout: hpc/cute/layout.md
      - Tensor: hpc/cute/tensor.md
    - HPC 101:
      - HPC 101: hpc/hpc101/index.md
      - 课堂实验 NVIDIA CUDA C: hpc/hpc101/cuda.md
  - Labs:
    - HPC lab2 向量化计算: labs/numpy.md
    - HPC lab2.5 手写 SIMD 向量化: labs/simd.md
    - HPC lab3 CUDA 使用基础: labs/cuda.md
    - HPC lab4 PCG Solver: labs/pcg.md
    - HPC lab5 简单神经网络训练与加速: labs/cnn.md