site_name: GoPoux's Notebook

theme:
  name: material
  language: 'zh'
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

plugins:
  - search

nav:
  - Home:
    - index.md
  - Notes:
    - notes/index.md
    - Note1:
      - note1: notes/note1.md
    - Note2:
      - note2: notes/note2.md