site_name: GoPoux's Notebook

theme:
  name: material
  language: 'zh'
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

nav:
  - Home:
    - index.md
  - HPC:
    - HPC/index.md