site_name: GoPoux 的笔记本
site_url: https://note.gopoux.cc/
repo_name: GoPoux4/notebook
repo_url: https://github.com/GoPoux4/notebook/
copyright: Copyright &copy; 2023-2024 GoPoux


theme:
  name: material
  language: 'zh'
  favicon: 'assert/ico/favicon.png'
  icon:
    repo: fontawesome/brands/github
    logo: material/notebook-outline
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
  font:
    text: Fira Sans
    code: Fira Mono

plugins:
  - search:
      separator: '[\s\u200b\-]'
      lang:
        - zh
        - en

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home:
    - index.md
  - Computer Science:
    - Computer Science: CS/index.md
    - CS/content.md
  - HPC:
    - HPC: HPC/index.md
    - HPC 101 labs:
      - HPC 101 labs: HPC/HPC 101 labs/index.md
      - 课堂实验 NVIDIA CUDA C: HPC/HPC 101 labs/cudaC.md
  - Labs:
    - HPC lab2 向量化计算: Labs/numpy.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GoPoux4
      name: My Github Page
    - icon: fontawesome/solid/rss
      link: https://www.cnblogs.com/syc233/
      name: My Cnblog Page

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
