site_name: GoPoux's Notebook
repo_url: https://github.com/GoPoux4/notebook
repo_name: GoPoux4/notebook

theme:
  name: material
  language: 'zh'
  favicon: 'assert/ico/favicon.png'
  icon:
    repo: fontawesome/brands/github
    logo: material/notebook-outline
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
  font:
    text: Fira Sans
    code: Fira Mono

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home:
    - index.md
  - Computer Science:
    - Computer Science: CS/index.md
  - HPC:
    - HPC: HPC/index.md