site_name: GoPoux 的笔记本
site_url: https://note.gopoux.cc/
repo_name: GoPoux4/notebook
repo_url: https://github.com/GoPoux4/notebook/
copyright: Copyright &copy; 2023-2024 GoPoux # <a href="https://beian.miit.gov.cn/" target="_blank">蜀ICP备2023017648号</a>

theme:
  name: material
  language: 'zh'
  favicon: 'assets/ico/favicon.png'
  icon:
    repo: fontawesome/brands/github
    logo: material/notebook-outline
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
  font: false

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: GoPoux4/notebook
      branch: master
  - git-authors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - neoteroi.cards # install using `pip install neoteroi-mkdocs`

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GoPoux4
      name: My Github Page
    - icon: fontawesome/solid/rss
      link: https://www.cnblogs.com/syc233/
      name: My Cnblog Page

extra_css:
  - css/neoteroi-mkdocs.css
  - css/counter.css
  - css/stylesheet.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
    - 友链: links.md
  - Computer Science:
    - Computer Science: cs/index.md
    - 数据结构:
      - 数据结构基础:
        - cs/fds/index.md
        - Agorithm Analysis: cs/fds/chapter1.md
        - Lists, Stacks and Queues: cs/fds/chapter2.md
        - Trees: cs/fds/chapter3.md
        - Union and Find: cs/fds/chapter4.md
        - Graphs: cs/fds/chapter5.md
        - Sorting: cs/fds/chapter6.md
        - Hashing: cs/fds/chapter7.md
      - 高级数据结构与算法分析:
        - cs/ads/index.md
        - AVL, Splay and Amortized Analysis: cs/ads/chapter1.md
        - Red-black Trees and B+ Trees: cs/ads/chapter2.md
        - Inverted File Index: cs/ads/chapter3.md
        - Leftist Heaps and Skew Heaps: cs/ads/chapter4.md
        - Binomial Queue: cs/ads/chapter5.md
        - Backtracking: cs/ads/chapter6.md
        - Divide and Conquer: cs/ads/chapter7.md
        - Dynamic Programming: cs/ads/chapter8.md
        - Greedy Algorithm: cs/ads/chapter9.md
        - NP Completeness: cs/ads/chapter10.md
        - Approximation: cs/ads/chapter11.md
        - Local Search: cs/ads/chapter12.md
        - Randomized Algorithms: cs/ads/chapter13.md
        - Parallel Algorithms: cs/ads/chapter14.md
        - External Sorting: cs/ads/chapter15.md
    - 计算机逻辑设计基础:
      - cs/computer_logic/index.md
      - 数字系统和信息: cs/computer_logic/chapter1.md
      - 组合逻辑电路: cs/computer_logic/chapter2.md
      - 组合逻辑电路设计: cs/computer_logic/chapter3.md
      - 时序逻辑电路: cs/computer_logic/chapter4.md
      - 数字硬件实现: cs/computer_logic/chapter5.md
      - 寄存器和寄存器传输: cs/computer_logic/chapter6.md
      - 内存基础: cs/computer_logic/chapter7.md
    - 数据库系统:
      - cs/database/index.md
      - 数据库系统概述: cs/database/chapter1.md
      - 关系模型: cs/database/chapter2.md
      - 复习: cs/database/review.md
    - 计算机组成与设计:
      - cs/co/index.md
      - 复习: cs/co/review.md
    - 面向对象程序设计:
      - cs/oop/index.md
      - 复习: cs/oop/review.md
    - 计算机视觉导论:
      - cs/cv/index.md
      - 线代知识回顾: cs/cv/chapter1.md
      - 图像的形成: cs/cv/chapter2.md
      - 图像的处理: cs/cv/chapter3.md
    - 量子计算理论基础与软件系统:
      - cs/quantum/index.md
      - 量子比特与量子门: cs/quantum/chapter1.md
      - 量子测量与量子图灵机: cs/quantum/chapter2.md
      - 量子算法: cs/quantum/chapter3.md
    - 软件工程与游戏设计:
      - cs/game/index.md
      - Introductions: cs/game/chapter1.md
      - Sprites and Randomness: cs/game/chapter2.md
      - Maze Algorithms: cs/game/chapter3.md
      - Final Lab: cs/game/final.md
  - Math:
    - Math: math/index.md
    - 概率论:
      - math/prob_theory/index.md
      - 事件及其概率: math/prob_theory/chapter1.md
      - 随机变量与分布函数: math/prob_theory/chapter2.md
      - 数字特征: math/prob_theory/chapter3.md
      - 概率极限定理: math/prob_theory/chapter4.md
  - HPC:
    - HPC: hpc/index.md
    - cute:
      - cute: hpc/cute/index.md
      - Layout: hpc/cute/layout.md
      - Tensor: hpc/cute/tensor.md
    - HPC 101:
      - HPC 101: hpc/hpc101/index.md
      - 课堂实验 NVIDIA CUDA C: hpc/hpc101/cuda.md
  - Others:
    - Others: others/index.md
    - 视唱练耳: others/sight_singing.md
    - 打开艺术之门——钢琴: others/piano.md
  - Labs:
    - HPC lab2 向量化计算: labs/numpy.md
    - HPC lab2.5 手写 SIMD 向量化: labs/simd.md
    - HPC lab3 CUDA 使用基础: labs/cuda.md
    - HPC lab4 PCG Solver: labs/pcg.md
    - HPC lab5 简单神经网络训练与加速: labs/cnn.md
  - Books:
    - 读书笔记: books/index.md
    - OSTEP:
      - OSTEP: books/ostep/index.md
      - Virtualization:
        - CPU 虚拟化：进程: books/ostep/chapter1/process.md
        # - CPU 虚拟化：进程调度: books/ostep/chapter1/scheduling.md
        # - 内存虚拟化：地址空间: books/ostep/chapter2/memory.md
        # - 内存虚拟化：分页: books/ostep/chapter2/paging.md
        # - 内存虚拟化：超越物理内存: books/ostep/chapter2/beyond.md
        # - VAX/VMS 虚拟内存系统: books/ostep/chapter2/vax_vms.md
  - CTF:
    - Writeups: ctf/writeups/zjuctf2024.md